package dionysus.wine.query;

public interface BasicInfoQuery {
	public String insert="INSERT INTO BASIC_INFO(BASIC_INFO_ID, BASIC_INFO_USERNAME, BASIC_INFO_PWD, BASIC_INFO_EMAIL)VALUES(BASIC_INFO_SEQ.NEXTVAL, ?, ?, ?)";
	public String login= "SELECT COUNT(*)FROM BASIC_INFO WHERE BASIC_INFO_USERNAME=? AND BASIC_INFO_PWD=?";
	public String basicInfoUsernameCheck="SELECT COUNT(*)FROM BASIC_INFO WHERE BASIC_INFO_USERNAME=?";
	public String update= "UPDATE BASIC_INFO SET BASIC_INFO_PWD=?, BASIC_INFO_EMAIL=? WHERE BASIC_INFO_USERNAME=?";
	public String selectByID="SELECT BASIC_INFO_USERNAME, BASIC_INFO_PWD, BASIC_INFO_EMAIL FROM BASIC_INFO WHERE BASIC_INFO_USERNAME=?";
	public String selectByUsernameOfCustomerId= "SELECT C.CUSTOMER_ID FROM CUSTOMER C, BASIC_INFO B WHERE B.BASIC_INFO_ID= C.BASIC_INFO_ID AND B.BASIC_INFO_USERNAME=?";
	public String selectByBasicInfoIdOfBaiscInfUsername="SELECT BASIC_INFO_ID FROM BASIC_INFO WHERE BASIC_INFO_USERNAME=?";
}
