package dionysus.wine.query;

public interface WineInfoQuery {
	   //  와인상품 전체리스트 조회
	   public String selectAll="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY FROM WINE_INFO)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	   //  단가높은순 조회
	   public String sellMax="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY FROM WINE_INFO ORDER BY WINE_INFO_PRICE ASC)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	   //  단가낮은순 조회
	   public String sellMin="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY FROM WINE_INFO ORDER BY WINE_INFO_PRICE DESC)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	   //  와인상품 Count
	   public String selectAllCount="SELECT COUNT(WINE_INFO_ID)FROM WINE_INFO";
	   //  와인상품 원산지별 조회
	   public String selectByOrigin="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY FROM WINE_INFO WHERE WINE_INFO_COUNTRY=?)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	   //  와인상품 원산지별 Count
	   public String selectByOriginCount="SELECT COUNT(WINE_INFO_ID)FROM WINE_INFO WHERE WINE_INFO_COUNTRY=?";
	   //  와인상품 추가
	   public String insert="INSERT INTO WINE_INFO(WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY)VALUES(WINE_INFO_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	   //  와인상품 정보삭제
	   public String delete="DELETE FROM WINE_INFO WHERE WINE_INFO_NAME=?";
	   //  와인상품 정보수정
	   public String update="UPDATE WINE_INFO SET WINE_INFO_PROFILE_PICTURE=?, WINE_INFO_PRICE=?, WINE_INFO_CAPACITY=?, WINE_INFO_COUNTRY=?, WINE_INFO_REGION=?, WINE_INFO_WINERY=?, WINE_INFO_IMPORTER=?, WINE_INFO_VINTAGE=?, WINE_INFO_GRAPES=?, WINE_INFO_ABV=?, WINE_INFO_TYPE=?, WINE_INFO_CLASSIFICATION=?, WINE_INFO_FLAVORS=?, WINE_INFO_SWEETNESS=?, WINE_INFO_ACIDITY=?, WINE_INFO_BODY=? WHERE WINE_INFO_NAME=? AND WINE_SELLER_ID=?";
	   //  회사리스트별 상품조회
	   public String selectByWineSeller="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_INFO_ID, WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY WHERE WINE_SELLER_ID=?)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	   //  회사별 COUNTS
	   public String selectByWineSellerCount="SELECT COUNT(WINE_SELLER_ID)FROM WINE_INFO";
	   //  와인번호별 와인정보 조회
	   public String selectByWineInfoId="SELECT WINE_INFO_NAME, WINE_INFO_PROFILE_PICTURE, WINE_INFO_PRICE, WINE_SELLER_ID, WINE_INFO_CAPACITY, WINE_INFO_COUNTRY, WINE_INFO_REGION, WINE_INFO_WINERY, WINE_INFO_IMPORTER, WINE_INFO_VINTAGE, WINE_INFO_GRAPES, WINE_INFO_ABV, WINE_INFO_TYPE, WINE_INFO_CLASSIFICATION, WINE_INFO_FLAVORS, WINE_INFO_SWEETNESS, WINE_INFO_ACIDITY, WINE_INFO_BODY WHERE WINE_INFO_ID=?";
	   //  BasicInfoUsername별 WineSellerId 찾기
	   public String selectByWineSellerId= "SELECT W.WINE_SELLER_ID FROM WINE_SELLER W, BASIC_INFO B WHERE B.BASIC_INFO_ID=W.BASIC_INFO_ID AND B.BASIC_INFO_USERNAME=?";
	   //  와인상품 번호별 와인업주번호 찾기
	   public String selectByWineSellerIdOfWineInfoId= "SELECT WINE_SELLER_ID FROM WINE_INFO WHERE WINE_INFO_ID=?";
}
