package dionysus.wine.query;

public interface WineReviewQuery {
	public String insertWineReview="INSERT INTO WINE_REVIEW(WINE_REVIEW_ID, WINE_REVIEW_CONTENT, WINE_REVIEW_RATINGS, CUSTOMER_ID, WINE_INFO_ID)VALUES(WINE_REVIEW_SEQ.NEXTVAL, ?, ?, ?, ?)";
	public String updateWineReview="UPDATE WINE_REVIEW SET WINE_REVIEW_CONTENT=?, WINREVIEW_RATINGS=? WHERE WINE_REVIEW_ID=? AND CUSTOMER_ID=? AND WINE_INFO_ID=?";
	public String deleteWineReview="DELETE FROM WINE_REVIEW WHERE WINE_REVIEW_ID=? AND CUSTOMER_ID=? AND WINE_INFO_ID=?";
	public String selectAllWineReview="SELECT WINE_REVIEW_ID, WINE_REVIEW_CONTENT, WINE_REVIEW_RATINGS, CUSTOMER_ID, WINE_INFO_ID FROM WINE_REVIEW";
}
