package dionysus.wine.query;

public interface WineOrderQuery {
	public String sellectAllWineOrder="SELECT T2.* FROM(SELECT ROWNUM RNUM, T1.* FROM(SELECT WINE_ORDER_ID, WINE_ORDER_DATE, WINE_ORDER_AMOUNT, CUSTOMER_ID, WINE_SELLER_ID FROM WINE_ORDER)T1)T2 WHERE RNUM BETWEEN ? AND ?";
	public String selectAllCount= "SELECT COUNT(WINE_ORDER_ID)FROM WINE_ORDER";
	public String wineOrderByMonth="SELECT WINE_ORDER_ID, WINE_ORDER_DATE, WINE_ORDER_AMOUNT, CUSTOMER_ID, WINE_SELLER_ID FROM WINE_ORDER WHERE TO_CHAR(WINE_ORDER_DATE, 'YYYY/MM')=?";
	//	OOOO년/OO월 입력
	public String wineOrderByDay= "SELECT WINE_ORDER_ID, WINE_ORDER_DATE, WINE_ORDER_AMOUNT, CUSTOMER_ID, WINE_SELLER_ID FROM WINE_ORDER WHERE TO_CHAR(WINE_ORDER_DATE, 'YYYY/MM/DD')=?";
	//	OOOO년/OO월/OO일 입력
	public String wineOrderByWineSeller= "SELECT WINE_ORDER_ID, WINE_ORDER_DATE, WINE_ORDER_AMOUNT, CUSTOMER_ID, WINE_SELLER_ID FROM WINE_ORDER WHERE WINE_SELLER_ID=?";
	public String wineOrderAmountByWineSeller= "SELECT SUM(WINE_ORDER_AMOUNT)FROM WINE_ORDER WHERE WINE_SELLER_ID=?";
	//	주문 판매량 건수 sum합만 나옵니다.
	public String wineOrderByMonthOfWineSeller="SELECT SUM(WINE_ORDER_AMOUNT)FROM WINE_ORDER WHERE TO_CHAR(WINE_ORDER_DATE, 'YYYY/MM')=? AND WINE_SELLER_ID=?";
	//	OOOO년/OO월, WINE_SELLER_ID =? 입력 시 주문 판매량 SUM값 조회
	public String wineOrderByDayOfWineSeller= "SELECT SUM(WINE_ORDER_AMOUNT)FROM WINE_ORDER WHERE TO_CHAR(WINE_ORDER_DATE, 'YYYY/MM/DD')=? AND WINE_SELLER_ID=?";
	//	OOOO년/OO월/OO일, WINE_SELLER_ID =? 입력 시 주문 판매량 SUM값 조회
	public String wineOrderByCustomer="SELECT W.WINE_ORDER_ID, W.WINE_ORDER_DATE, W.WINE_ORDER_AMOUNT, C.CUSTOMER_ID, S.WINE_SELLER_ID, C.CUSTOMER_RRN, C.CUSTOMER_ADDRESS, C.CUSTOMER_NAME, C.CUSTOMER_TEL, C.CUSTOMER_GENDER, C.CUSTOMER_ACCOUNT_NO, C.CUSTOMER_JOB, C.CUSTOMER_ACTIVATED FROM WINE_ORDER W, CUSTOMER C, WINE_SELLER S WHERE W.CUSTOMER_ID=C.CUSTOMER_ID AND W.WINE_SELLER_ID= S.WINE_SELLER_ID AND W.CUSTOMER_ID=? AND W.WINE_SELLER_ID=?";
	public String insertWineOrder="INSERT INTO WINE_ORDER(WINE_ORDER_ID, WINE_ORDER_DATE, WINE_ORDER_AMOUNT, CUSTOMER_ID, WINE_SELLER_ID)VALUES(WINE_ORDER_SEQ.NEXTVAL, ?, ?, ?, ?)";
	public String deleteWineOrder="DELETE FROM WINE_ORDER WHERE WINE_ORDER_ID=?";
	//	와인업주 번호 조회
	public String selectByWineSellerId="SELECT WI.WINE_SELLER_ID, WO.WINE_ORDER_ID FROM WINE_INFO WI, WINE_ORDER WO, WINE_ORDER_INFO WOI WHERE WO.WINE_ORDER_ID=WOI.WINE_ORDER_ID AND WOI.WINE_INFO_ID= WI.WINE_INFO_ID";
}
